DROP TABLE users;
DROP TABLE transactions;

CREATE TABLE users(
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    username TEXT NOT NULL,
    hash TEXT NOT NULL,
    bet NUMERIC NOT NULL DEFAULT 5.0,
    balance NUMERIC NOT NULL DEFAULT 1000.00
);

CREATE TABLE transactions(
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    user_id INTEGER NOT NULL,
    bet NUMERIC NOT NULL,
    win NUMERIC NOT NULL,
    date TEXT NOT NULL,
    FOREIGN KEY(user_id) REFERENCES users(id)
);
